### ISSUE TITLE
Contract query returns royalty: null

### ISSUE THREAD

**Issue by jamesmurdza** [public-awesome/stargaze-contracts#144]
When creating a new contract initialization is successful but when querying collection_info, royalty is null.

2458eb22c91cb8856e09505875ba485ed1688c42 refactors the royalty info state in several places, could this have caused a bug?

**Comment by shanev** [comment]
@jamesmurdza How are you querying? Mind pasting the query?

**Comment by shanev** [comment]
@jamesmurdza The query may have changed since you used it last. Here's the updated one: https://github.com/public-awesome/stargaze-contracts/blob/main/contracts/sg721/src/contract.rs#L202

**Comment by jamesmurdza** [comment]
await client.queryContractSmart(addr, { collection_info: {} });

OK, I don't get royalty: null if I query a contract I created on Friday. So it must be in the contract itself.

Is it possible that this could be from validation failure? Nothing changed in my config except for the lines that also changed in the example config.

**Comment by shanev** [comment]
Do you know what `codeId` you used for sg721? And do you happen to have the minter contract version number when it was instantiated?

**Comment by jamesmurdza** [comment]
The one that is giving royalty: null is from earlier today, so 76/77. The previous one I tried (which worked), would have been 68/69.

**Comment by shanev** [comment]
Tooling wasn't updated to work w/ royalty updates. Fixed by https://github.com/public-awesome/stargaze-tools/pull/128.

**Comment by jamesmurdza** [comment]
Thank you Shane!
