### ISSUE TITLE
export `MembersListResponse` for RoyaltyGroup contract

### ISSUE THREAD

**Issue by pyramation** [public-awesome/stargaze-contracts#279]
hi! learning rust here 😅 and want to fix the contract but can't figure out how to import a type.

https://github.com/public-awesome/stargaze-contracts/blob/main/contracts/royalty-group/src/msg.rs#L41-L45

```rs
/// Returns MembersListResponse
    ListMembers {
        start_after: Option<String>,
        limit: Option<u32>,
    },
```

we need to import `QueryMsg::ListMembers` into the [`examples/schema.rs`](https://github.com/public-awesome/stargaze-contracts/blob/main/contracts/royalty-group/examples/schema.rs) file and export it as `MembersListResponse` 

If I learn how to do this, I'm happy to fix all the other contracts and fields

**Comment by Callum-A** [comment]
So I believe `MembersListResponse` is actually located under `cw4-group` which is what this contract forks. So to import it, it would be `use::cw4::MemberListResponse` hope this helps!

**Comment by pyramation** [comment]
Thanks @Callum-A ! I'll look into this, much appreciated :)
